name: Hello world

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set AWS environment credentials
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: bash .github/scripts/test.sh

      - name: Set AWS environment credentials
        run: echo "😀$ENVIRONMENT"
